AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 130

Metrics/ClassLength:
  Max: 600

Metrics/MethodLength:
  Max: 35

Metrics/AbcSize:
  Max: 45

Metrics/CyclomaticComplexity:
  Max: 17

Metrics/PerceivedComplexity:
  Max: 15

Metrics/ParameterLists:
  Max: 10

Naming/MethodParameterName:
  AllowedNames:
    - x
    - n
    - v
    - s
    - sz
    - px
    - m

Naming/VariableNumber:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/NumericPredicate:
  Enabled: false
